In [22]:
import pandas as pd
import numpy as np

In [2]:
web_stats = {'Day':[1,2,3,4,5,6],
             'Visitors':[43,34,65,56,29,76],
             'Bounce Rate':[65,67,78,65,45,52]}

df = pd.DataFrame(web_stats)
df.head()

Bounce Rate  Day  Visitors
0           65    1        43
1           67    2        34
2           78    3        65
3           65    4        56
4           45    5        29

In [3]:
df = pd.read_excel('employees.xlsx', sheet_name='Sheet1')

In [4]:
df.head()

EMPLOYEE_ID FIRST_NAME LAST_NAME     EMAIL  PHONE_NUMBER  HIRE_DATE  \
0          101      Neena   Kochhar  NKOCHHAR  515.123.4568 1989-09-21   
1          102        Lex   De Haan   LDEHAAN  515.123.4569 1993-01-13   
2          103  Alexander    Hunold   AHUNOLD  590.423.4567 1990-01-03   
3          104      Bruce     Ernst    BERNST  590.423.4568 1991-05-21   
4          105      David    Austin   DAUSTIN  590.423.4569 1997-06-25   

    JOB_ID  SALARY  COMMISSION_PCT  MANAGER_ID  DEPARTMENT_ID  
0    AD_VP   17000             NaN         100           90.0  
1    AD_VP   17000             NaN         100           90.0  
2  IT_PROG    9000             NaN         102           60.0  
3  IT_PROG    6000             NaN         103           60.0  
4  IT_PROG    4800             NaN         103           60.0

In [5]:
df.columns

Index(['EMPLOYEE_ID', 'FIRST_NAME', 'LAST_NAME', 'EMAIL', 'PHONE_NUMBER',
       'HIRE_DATE', 'JOB_ID', 'SALARY', 'COMMISSION_PCT', 'MANAGER_ID',
       'DEPARTMENT_ID'],
      dtype='object')

In [6]:
df = df.drop("COMMISSION_PCT", axis=1)

In [7]:
df.head()

EMPLOYEE_ID FIRST_NAME LAST_NAME     EMAIL  PHONE_NUMBER  HIRE_DATE  \
0          101      Neena   Kochhar  NKOCHHAR  515.123.4568 1989-09-21   
1          102        Lex   De Haan   LDEHAAN  515.123.4569 1993-01-13   
2          103  Alexander    Hunold   AHUNOLD  590.423.4567 1990-01-03   
3          104      Bruce     Ernst    BERNST  590.423.4568 1991-05-21   
4          105      David    Austin   DAUSTIN  590.423.4569 1997-06-25   

    JOB_ID  SALARY  MANAGER_ID  DEPARTMENT_ID  
0    AD_VP   17000         100           90.0  
1    AD_VP   17000         100           90.0  
2  IT_PROG    9000         102           60.0  
3  IT_PROG    6000         103           60.0  
4  IT_PROG    4800         103           60.0

In [9]:
#df['FIRST_NAME']

In [10]:
#df.EMAIL

In [11]:
#df[['FIRST_NAME','EMAIL']]

In [12]:
df.to_csv('employees.csv')

In [16]:
# https://simple.wikipedia.org/wiki/List_of_U.S._states
movie = pd.read_html("https://en.wikipedia.org/wiki/List_of_highest-grossing_films")
print(type(movie))
#print(movie[0])

<class 'list'>


In [17]:
movie_df = movie[0]
movie_df.columns = movie_df.iloc[0]
movie_df.drop(movie_df.index[[0]] , inplace=True)
movie_df.head(2)

0 Rank Peak    Title Worldwide gross  Year Reference(s)
1    1    1   Avatar  $2,787,965,087  2009   [# 1][# 2]
2    2    1  Titanic  $2,187,463,944  1997   [# 3][# 4]

In [3]:
df1 = pd.DataFrame({'HPI':[80,85,88,85],
                    'Int_rate':[2, 3, 2, 2],
                    'US_GDP_Thousands':[50, 55, 65, 55]},
                   index = [2001, 2002, 2003, 2004])

df2 = pd.DataFrame({'HPI':[80,85,88,85],
                    'Int_rate':[2, 3, 2, 2],
                    'US_GDP_Thousands':[50, 55, 65, 55]},
                   index = [2005, 2006, 2007, 2008])

df3 = pd.DataFrame({'HPI':[80,85,88,85],
                    'Int_rate':[2, 3, 2, 2],
                    'Low_tier_HPI':[50, 52, 50, 53]},
                   index = [2001, 2002, 2003, 2004])

In [4]:
pd.concat([df1,df2]).head(10)

HPI  Int_rate  US_GDP_Thousands
2001   80         2                50
2002   85         3                55
2003   88         2                65
2004   85         2                55
2005   80         2                50
2006   85         3                55
2007   88         2                65
2008   85         2                55

### numpy


In [16]:
wines1 = pd.read_csv('wines.csv', sep=';', header=0)

In [19]:
wines1

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70            0             1.9      0.076   
1            7.8              0.88            0             2.6      0.098   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                   11                    34   0.9978  3.51       0.56   
1                   25                    67   0.9968  3.20       0.68   

   alcohol  quality  
0      9.4        5  
1      9.8        5

In [26]:
wines.shape

(2, 12)

In [17]:
empty_array = np.zeros((3,4))
empty_array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
np.random.rand(3,4)

array([[0.59207555, 0.67708679, 0.91720738, 0.14245642],
       [0.71405735, 0.49494845, 0.57847744, 0.19758399],
       [0.94844793, 0.0918517 , 0.75770375, 0.8963448 ]])

In [24]:
wines = np.genfromtxt("wines.csv", delimiter=";", skip_header=1)

In [25]:
wines[1].mean()

10.254566666666667

### 1-Dimensional NumPy Arrays

In [44]:
third_wine = wines[1,:]

In [45]:
third_wine

array([ 7.8   ,  0.88  ,  0.    ,  2.6   ,  0.098 , 25.    , 67.    ,
        0.9968,  3.2   ,  0.68  ,  9.8   ,  5.    ])

In [46]:
third_wine[1]

0.88

### N-Dimensional NumPy Arrays

In [29]:
year_one = [
    [500,505,490],
    [810,450,678],
    [234,897,430],
    [560,1023,640]
]

In [32]:
earnings = [
            [
                [500,505,490],
                [810,450,678],
                [234,897,430],
                [560,1023,640]
            ],
            [
                [600,605,490],
                [345,900,1000],
                [780,730,710],
                [670,540,324]
            ]
          ]

In [33]:
earnings = np.array(earnings)
earnings[0,0,0]

500

In [34]:
earnings[0,0,1]

505

In [35]:
earnings.shape

(2, 4, 3)

### Map, filter, Reduce

In [36]:
def add_one(this_item):
    return this_item + 1

In [37]:
numbers = [1,2,3,4,5]
res = map(add_one, numbers)

In [38]:
for i in res:
    print(i)

2
3
4
5
6


In [39]:
def is_even(this_item):
    return this_item % 2 == 0

In [40]:
res = filter(is_even,numbers)

In [41]:
for i in res:
    print(i)

2
4


In [42]:
def add_item(first, second):
    return first + second

In [43]:
from functools import reduce
reduce(add_item, numbers)

15

In [45]:
import dbms
import pandas as pd
con = dbms.connect.oracle("scott", "tiger", "orcl", host="10.188.193.152", port=1521)
cs = con.cursor()
cs.execute('SELECT * FROM ' + "LOCATIONS")

columns = [x[0] for x in cs.description]

pdf = pd.DataFrame(cs.fetchall(), columns=columns)

con.close()

DatabaseError: DPI-1047: 64-bit Oracle Client library cannot be loaded: "The specified module could not be found". See https://oracle.github.io/odpi/doc/installation.html#windows for help

In [26]:
pdf.head()

LOCATION_ID STREET_ADDRESS POSTAL_CODE       CITY STATE_PROVINCE COUNTRY_ID
0        5000      bangalore      560017  marathali            btm         BA
1        5005      bangalore      560018  marathalA           btms         CA
2        5006     bangalore1      560019  marathalb           btml         DA
3        5007     bangalore2      560020  marathalc           btmK         EA
4          50     bangalore3      560014  marathalc           btme         MA